### ISSUE TITLE
Using Image, Button, etc in widget not working

### ISSUE THREAD

**Issue by davidskaarup** [rclai/React-Native-Today-Widget#2]
I managed to get a widget working in my app by following your guide, but I'm only able to use View and Text components. If I try to use e.g. Image, Button or TouchableOpacity the widget does not render anything. Do you have a solution to this? @rclai @dewski

**Comment by davidskaarup** [comment]
Never mind, I must have made some mistake, because it's working now :)

**Comment by svenadlung** [comment]
@davidskaarup Just wondering what was your Button doing? Maybe you can help on this one (https://github.com/rclai/React-Native-Today-Widget/issues/3)?
